import { SeasonKickQueryModel } from '@interfaces/stats/query.model';
import { safeConvertFloat, safeConvertInt} from '@player/utils/safeConvert.utils';

export class SeasonKickDto {
   public fg_att?: number;
   public fg_made?: number;
   public fg_missed?: number;
   public fg_blocked?: number;
   public fg_pct?: number;
   public fg_long?: number;
   public fg_made_0_19?: number;
   public fg_made_20_29?: number;
   public fg_made_30_39?: number;
   public fg_made_40_49?: number;
   public fg_made_50_59?: number;
   public fg_made_60_?: number;
   public fg_missed_0_19?: number;
   public fg_missed_20_29?: number;
   public fg_missed_30_39?: number;
   public fg_missed_40_49?: number;
   public fg_missed_50_59?: number;
   public fg_missed_60_?: number;
   public fg_made_distance?: number;
   public fg_missed_distance?: number;
   public fg_blocked_distance?: number;
   public fg_made_list?: string;
   public fg_missed_list?: string;
   public fg_blocked_list?: string;
   public gwfg_att?: number;
   public gwfg_distance?: number;
   public gwfg_made?: number;
   public gwfg_missed?: number;
   public gwfg_blocked?: number;
   public pat_att?: number;
   public pat_made?: number;
   public pat_missed?: number;
   public pat_blocked?: number;
   public pat_pct?: number;

   constructor(stats?: SeasonKickQueryModel) {
       this.fg_att = safeConvertInt(stats?.fg_att);
       this.fg_made = safeConvertInt(stats?.fg_made);
       this.fg_missed = safeConvertInt(stats?.fg_missed);
       this.fg_blocked = safeConvertInt(stats?.fg_blocked);
       this.fg_pct = safeConvertInt(stats?.fg_pct);
       this.fg_long = safeConvertInt(stats?.fg_long);
       this.fg_made_0_19 = safeConvertInt(stats?.fg_made_0_19);
       this.fg_made_20_29 = safeConvertInt(stats?.fg_made_20_29);
       this.fg_made_30_39 = safeConvertInt(stats?.fg_made_30_39);
       this.fg_made_40_49 = safeConvertInt(stats?.fg_made_40_49);
       this.fg_made_50_59 = safeConvertInt(stats?.fg_made_50_59);
       this.fg_made_60_ = safeConvertInt(stats?.fg_made_60_);
       this.fg_missed_0_19 = safeConvertInt(stats?.fg_missed_0_19);
       this.fg_missed_20_29 = safeConvertInt(stats?.fg_missed_20_29);
       this.fg_missed_30_39 = safeConvertInt(stats?.fg_missed_30_39);
       this.fg_missed_40_49 = safeConvertInt(stats?.fg_missed_40_49);
       this.fg_missed_50_59 = safeConvertInt(stats?.fg_missed_50_59);
       this.fg_missed_60_ = safeConvertInt(stats?.fg_missed_60_);
       this.fg_made_distance = safeConvertFloat(stats?.fg_made_distance);
       this.fg_missed_distance = safeConvertFloat(stats?.fg_missed_distance);
       this.fg_blocked_distance = safeConvertFloat(stats?.fg_blocked_distance);
       this.gwfg_att = safeConvertInt(stats?.gwfg_att);
       this.gwfg_distance = safeConvertFloat(stats?.gwfg_distance);
       this.gwfg_made = safeConvertInt(stats?.gwfg_made);
       this.gwfg_missed = safeConvertInt(stats?.gwfg_missed);
       this.gwfg_blocked = safeConvertInt(stats?.gwfg_blocked);
       this.pat_att = safeConvertInt(stats?.pat_att);
       this.pat_made = safeConvertInt(stats?.pat_made);
       this.pat_missed = safeConvertInt(stats?.pat_missed);
       this.pat_blocked = safeConvertInt(stats?.pat_blocked);
       this.pat_pct = safeConvertFloat(stats?.pat_pct);
   }
}