export const AuthSchema = 'auth'
export const NFLSchema = 'nfl'

export const BioTable = 'player_bio';
export const LeagueTable = 'player_league';
export const PlayerTable = 'players';
export const SeasonAdvDefTable = 'season_adv_stats_def';
export const SeasonAdvPassTable = 'season_adv_stats_pass';
export const SeasonAdvRecTable = 'season_adv_stats_rec';
export const SeasonAdvRushTable = 'season_adv_stats_rush';
export const SeasonDefTable = 'season_stats_def';
export const SeasonKickTable = 'season_stats_kick';
export const SeasonPassTable = 'season_stats_pass';
export const SeasonRecTable = 'season_stats_rec';
export const SeasonRushTable = 'season_stats_rush';
export const SeasonNextGenPassTable = 'season_nextgen_stats_pass';
export const SeasonNextGenRecTable = 'season_nextgen_stats_rec';
export const SeasonNextGenRushTable = 'season_nextgen_stats_rush';
export const SeasonStatTable = 'player_season_stats';
export const UnmatchedPlayerStatsTable = 'unmatched_player_stats';
export const WeeklyDefTable = 'weekly_stats_def';
export const WeeklyKickTable = 'weekly_stats_kick';
export const WeeklyPassTable = 'weekly_stats_pass';
export const WeeklyRecTable = 'weekly_stats_rec';
export const WeeklyRushTable = 'weekly_stats_rush';
export const WeeklyAdvDefTable = 'weekly_adv_stats_def';
export const WeeklyAdvPassTable = 'weekly_adv_stats_pass';
export const WeeklyAdvRecTable = 'weekly_adv_stats_rec';
export const WeeklyAdvRushTable = 'weekly_adv_stats_rush';
export const WeeklyNextGenPassTable = 'weekly_nextgen_stats_pass';
export const WeeklyNextGenRecTable = 'weekly_nextgen_stats_rec';
export const WeeklyNextGenRushTable = 'weekly_nextgen_stats_rush';
export const WeeklyStatTable = 'player_weekly_stats';
export const TeamTable = 'teams';
export const UserTable = 'users';

export const SeasonDefView = 'player_season_def_view';
export const SeasonKickView = 'player_season_kick_view';
export const SeasonPassView = 'player_season_pass_view';
export const SeasonRecView = 'player_season_rec_view';
export const SeasonRushView = 'player_season_rush_view';

export const DraftTeamId = 'draft_team_id';
export const PlayerFullName = 'full_name';
export const PlayerPFR = 'pfr_id';
export const PlayerId = 'player_id';
export const PlayerGSIS = 'gsis_id';
export const PlayerSmartId = "smart_id";
export const OpponentId = 'opponent_id';
export const SeasonStatId = 'player_season_id';
export const TeamId = 'team_id';
export const WeeklyStatId = 'player_weekly_id';

export const BioModelLabel = 'bio';
export const DraftTeamModelLabel = 'draftTeam';
export const LeagueModelLabel = 'league';
export const PlayerModelLabel = 'Player';
export const OpponentModelLabel = 'opponent';
export const SeasonModelLabel = 'seasonStats';
export const SeasonAdvDefModelLabel = 'seasonAdvDef';
export const SeasonAdvPassModelLabel = 'seasonAdvPass';
export const SeasonAdvRecModelLabel = 'seasonAdvRec';
export const SeasonAdvRushModelLabel = 'seasonAdvRush';
export const SeasonDefModelLabel = 'seasonDef';
export const SeasonKickModelLabel = 'seasonKick';
export const SeasonNextGenPassModelLabel = 'weeklyNextGenPass';
export const SeasonNextGenRecModelLabel = 'weeklyNextGenRec';
export const SeasonNextGenRushModelLabel = 'weeklyNextGenRush';
export const SeasonPassModelLabel = 'seasonPass';
export const SeasonRecModelLabel = 'seasonRec';
export const SeasonRushModelLabel = 'seasonRush';
export const TeamModelLabel = 'teamInfo';
export const UnmatchedPlayerStatModelLabel = 'unmatchedPlayerStats';
export const WeeklyModelLabel = 'weeklyStats';
export const WeeklyDefModelLabel = 'weeklyDef';
export const WeeklyKickModelLabel = 'weeklyKick';
export const WeeklyPassModelLabel = 'weeklyPass';
export const WeeklyRecModelLabel = 'weeklyRec';
export const WeeklyRushModelLabel = 'weeklyRush';
export const WeeklyNextGenPassModelLabel = 'weeklyNextGenPass';
export const WeeklyNextGenRecModelLabel = 'weeklyNextGenRec';
export const WeeklyNextGenRushModelLabel = 'weeklyNextGenRush';
export const WeeklyAdvDefModelLabel = 'weeklyAdvDef';
export const WeeklyAdvPassModelLabel = 'weeklyAdvPass';
export const WeeklyAdvRecModelLabel = 'weeklyAdvRec';
export const WeeklyAdvRushModelLabel = 'weeklyAdvRush';

export const TeamForeignKey = { foreignKey: { name: TeamId } };
export const OpponentForeignKey = { as: OpponentModelLabel , foreignKey: { name: OpponentId } };
export const PlayerForeignKey = { foreignKey: { name: PlayerId } };
export const PlayerSeasonForeignKey = { foreignKey: { name: SeasonStatId } };
export const PlayerWeeklyForeignKey = { foreignKey: { name: WeeklyStatId } };
export const PlayerSeasonStatForeignKey = { sourceKey: 'season', foreignKey: { name: 'season' } };

export const LeagueTeamForeignKey = { foreignKey: { name: TeamId } };
export const LeagueDraftTeamForeignKey = { as: DraftTeamModelLabel, foreignKey: { name: DraftTeamId } };

// Procedures
export const CalcSeasonStats = 'calc_season_stats';
export const CalcSeasonDefStats = 'calc_season_def_stats';
export const CalcSeasonKickStats = 'calc_season_kick_stats';
export const CalcSeasonPassStats = 'calc_season_pass_stats';
export const CalcSeasonRecStats = 'calc_season_rec_stats';
export const CalcSeasonRushStats = 'calc_season_rush_stats';
export const CalcSeasonNextGenPassStats = 'calc_season_nextgen_pass_stats';
export const CalcSeasonNextGenRecStats = 'calc_season_nextgen_rec_stats';
export const CalcSeasonNextGenRushStats = 'calc_season_nextgen_rush_stats';
export const CleanPlayerData = 'clean_player_data';