export enum CareerStatus {
    ActiveOnly = 'Active',
    All = 'All',
    InactiveOnly = 'Inactive',
  }
  
  export enum PositionGroup {
    DB = 'DB',
    DL = 'DL',
    LB = 'LB',
    OL = 'OL',
    RB = 'RB',  
    SPEC = 'SPEC',
    TE = 'TE',
    WR = 'WR',
    QB = 'QB',
  }
  
  export enum Position {
    C = 'C',
    CB = 'CB',
    DB = 'DB',
    DE = 'DE',
    DL = 'DL',
    DT = 'DT',
    FB = 'FB',
    FS = 'FS',
    G = 'G',
    HB = 'HB',
    ILB = 'ILB',
    K = 'K',
    KR = 'KR',
    LB = 'LB',
    LS = 'LS',
    MLB = 'MLB',
    NT = 'NT',
    OG = 'OG',
    OL = 'OL',
    OT = 'OT',
    OLB = 'OLB',
    P = 'P',
    PR = 'PR',
    RB = 'RB',
    S = 'S',
    SAF = 'SAF',
    SPEC = 'SPEC',
    SS = 'SS',
    T = 'T',
    TE = 'TE',
    WR = 'WR',
    QB = 'QB',
  }