export interface WeeklyAdvDefQueryModel {
    id?: number,
    player_weekly_id?: number,
    interceptions?: number,
    targets?: number,
    completions_allowed?: number,
    completion_pct?: number,
    yards_allowed?: number,
    yards_allowed_per_cmp?: number,
    yards_allowed_per_tgt?: number,
    rec_td_allowed?: number,
    passer_rating_allowed?: number,
    adot?: number,
    air_yards_completed?: number,
    yards_after_catch?: number,
    blitzed?: number,
    hurried?: number,
    pressures?: number,
    tackles_combined?: number,
    tackles_missed?: number,
    tackles_missed_pct?: number,
    created_date?: Date,
    last_modified?: Date,
}

export interface WeeklyAdvPassQueryModel {
    id?: number,
    player_weekly_id?: number,
    pass_drops?: number,
    pass_drop_pct?: number,
    rec_drop?: number,
    rec_drop_pct?: number,
    bad_throws?: number,
    bad_throw_pct?: number,
    blitzed?: number,
    hurried?: number,
    hit?: number,
    pressured?: number,
    pressured_pct?: number,
    created_date?: Date,
    last_modified?: Date,
}

export interface WeeklyAdvRecQueryModel {
    id?: number,
    player_weekly_id?: number,
    broken_tackles?: number,
    drops?: number,
    drop_pct?: number,
    interceptions?: number,
    qb_rating?: number,
    created_date?: Date,
    last_modified?: Date,
}

export interface WeeklyAdvRushQueryModel {
    id?: number,
    player_weekly_id?: number,
    yards_before_contact?: number,
    yards_before_contact_avg?: number,
    yards_after_contact?: number,
    yards_after_contact_avg?: number,
    broken_tackles?: number,
    created_date?: Date,
    last_modified?: Date,
}

export interface SeasonAdvDefQueryModel {
    id?: number,
    player_season_id?: number,
    interceptions?: number,
    targets?: number,
    completions_allowed?: number,
    completion_pct?: number,
    yards_allowed?: number,
    yards_allowed_per_cmp?: number,
    yards_allowed_per_tgt?: number,
    tds_allowed?: number,
    passer_rating_allowed?: number,
    adot?: number,
    air_yards_completed?: number,
    yards_after_catch?: number,
    blitzed?: number,
    hurried?: number,
    qbkd?: number,
    sacks?: number,
    pressures?: number,
    tackles_combined?: number,
    tackles_missed?: number,
    tackles_missed_pct?: number,
    created_date?: Date,
    last_modified?: Date,
}

export interface SeasonAdvPassQueryModel {
    id?: number,
    player_season_id?: number,
    attempts?: number,
    throw_aways?: number,
    spikes?: number,
    drops?: number,
    drop_pct?: number,
    bad_throws?: number,
    bad_throw_pct?: number,
    pocket_time?: number,
    blitzed?: number,
    hurried?: number,
    hit?: number,
    pressured?: number,
    pressured_pct?: number,
    batted_balls?: number,
    on_tgt_throws?: number,
    on_tgt_throws_pct?: number,
    rpo_plays?: number,
    rpo_yards?: number,
    rpo_pass_attempts?: number,
    rpo_pass_yards?: number,
    rpo_rush_attempts?: number,
    rpo_rush_yards?: number,
    pa_pass_attempts?: number,
    pa_pass_yards?: number,
    created_date?: Date,
    last_modified?: Date,
}

export interface SeasonAdvRecQueryModel {
    id?: number,
    player_season_id?: number,
    targets?: number,
    receptions?: number,
    yards?: number,
    tds?: number,
    longest_rec?: number,
    air_yards?: number,
    air_yards_avg?: number,
    yards_after_contact?: number,
    yards_after_contact_avg?: number,
    adot?: number,
    broken_tackles?: number,
    broken_tackles_avg?: number,
    drops?: number,
    drop_pct?: number,
    interceptions?: number,
    qb_rating?: number,
    created_date?: Date,
    last_modified?: Date,
}

export interface SeasonAdvRushQueryModel {
    id?: number,
    player_season_id?: number,
    attempts?: number,
    yards?: number,
    tds?: number,
    longest_rush?: number,
    yards_before_contact?: number,
    yards_before_contact_avg?: number,
    yards_after_contact?: number,
    yards_after_contact_avg?: number,
    broken_tackles?: number,
    broken_tackles_avg?: number,
    created_date?: Date,
    last_modified?: Date,
}