export interface WeeklyNextGenPassQueryModel {
    id?: number,
    player_weekly_id?: number,
    aggressiveness?: number,
    avg_time_to_throw?: number,
    avg_air_distance?: number,
    max_air_distance?: number,
    avg_completed_air_yards?: number,
    avg_intended_air_yards?: number,
    avg_air_yards_to_sticks?: number,
    max_completed_air_distance?: number,
    passer_rating?: number,
    completion_pct?: number,
    expected_completion_pct?: number,
    completions_above_expectation_pct?: number,
    created_date?: Date,
    last_modified?: Date,
}

export interface WeeklyNextGenRecQueryModel {
    id?: number,
    player_weekly_id?: number,
    avg_cushion?: number,
    avg_intended_air_yards_pct?: number,
    avg_separation?: number,
    avg_intended_air_yards?: number,
    catch_pct?: number,
    share_of_intended_air_yards_pct?: number,
    avg_yac?: number,
    avg_expected_yac?: number,
    avg_yac_above_expectation?: number,
    created_date?: Date,
    last_modified?: Date,
}

export interface WeeklyNextGenRushQueryModel {
    id?: number,
    player_weekly_id?: number,
    efficiency?: number,
    attempts_gte_eight_defenders_pct?: number,
    avg_time_to_los?: number,
    expected_yards?: number,
    yards_over_expected?: number,
    avg_yards?: number,
    yards_over_expected_per_att?: number,
    yards_over_expected_pct?: number,
    created_date?: Date,
    last_modified?: Date,
}
