export interface WeeklyDefQueryModel {
    id?: number,
    player_weekly_id?: number,
    tackles?: number,
    tackles_solo?: number,
    tackle_with_assists?: number,
    tackle_assists?: number,
    tackles_for_loss?: number,
    tackles_for_loss_yards?: number,
    fumbles_forced?: number,
    sacks?: number,
    sack_yards?: number,
    qb_hits?: number,
    interceptions?: number,
    interception_yards?: number,
    pass_defended?: number,
    tds?: number,
    fumbles?: number,
    fumble_recovery_own?: number,
    fumble_recovery_yards_own?: number,
    fumble_recovery_opp?: number,
    fumble_recovery_yards_opp?: number,
    safety?: number,
    penalty?: number,
    penalty_yards?: number,
    created_date?: Date,
    last_modified?: Date,
}

export interface WeeklyKickQueryModel {
    id?: number,
    player_weekly_id?: number,
    fg_att?: number,
    fg_made?: number,
    fg_missed?: number,
    fg_blocked?: number,
    fg_pct?: number,
    fg_long?: number,
    fg_made_0_19?: number,
    fg_made_20_29?: number,
    fg_made_30_39?: number,
    fg_made_40_49?: number,
    fg_made_50_59?: number,
    fg_made_60_?: number,
    fg_missed_0_19?: number,
    fg_missed_20_29?: number,
    fg_missed_30_39?: number,
    fg_missed_40_49?: number,
    fg_missed_50_59?: number,
    fg_missed_60_?: number,
    fg_made_distance?: number,
    fg_missed_distance?: number,
    fg_blocked_distance?: number,
    fg_made_list?: string,
    fg_missed_list?: string,
    fg_blocked_list?: string,
    gwfg_att?: number,
    gwfg_distance?: number,
    gwfg_made?: number,
    gwfg_missed?: number,
    gwfg_blocked?: number,
    pat_att?: number,
    pat_made?: number,
    pat_missed?: number,
    pat_blocked?: number,
    pat_pct?: number,
    created_date?: Date,
    last_modified?: Date,
}

export interface WeeklyPassQueryModel {
    id?: number,
    player_weekly_id?: number,
    attempts?: number,
    completions?: number,
    pass_yards?: number,
    pass_yards_after_catch?: number,
    pass_air_yards?: number,
    pass_air_conversion_ratio?: number,
    pass_first_down?: number,
    dakota?: number,
    pass_epa?: number,
    pass_tds?: number,
    pass_two_pt_conversions?: number,
    interceptions?: number,
    sacks?: number,
    sack_yards?: number,
    sack_fumbles?: number,
    sack_fumbles_lost?: number,
    created_date?: Date,
    last_modified?: Date,
}

export interface WeeklyRecQueryModel {
    id?: number,
    player_weekly_id?: number,
    targets?: number,
    receptions?: number,
    target_share?: number,
    rec_yards?: number,
    rec_yards_after_catch?: number,
    rec_air_yards?: number,
    rec_air_yards_share?: number,
    rec_air_conversion_ratio?: number,
    weighted_opportunity_rating?: number,
    rec_epa?: number,
    rec_tds?: number,
    rec_two_pt_conversions?: number,
    rec_first_downs?: number,
    rec_fumbles?: number,
    rec_fumbles_lost?: number,
    created_date?: Date,
    last_modified?: Date,
}

export interface WeeklyRushQueryModel {
    id?: number,
    player_weekly_id?: number,
    carries?: number,
    rush_yards?: number,
    rush_first_downs?: number,
    rush_epa?: number,
    rush_tds?: number,
    rush_two_pt_conversions?: number,
    rush_fumbles?: number,
    rush_fumbles_lost?: number,
    special_teams_tds?: number,
    created_date?: Date,
    last_modified?: Date,
}